name: school_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  url_launcher: ^6.3.2
  provider: ^6.1.5+1
  intl: ^0.20.2
  font_awesome_flutter: ^10.12.0
  flutter_pdfjs_viewer: ^0.0.5
  fl_chart: ^1.1.1
  syncfusion_flutter_chat: ^31.2.4
  syncfusion_flutter_charts: ^31.2.4
  table_calendar: ^3.2.0
  uuid: ^4.5.2
  pdf: ^3.11.3
  printer: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
